# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: purchase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='purchase.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n\x0epurchase.proto\x12\x02pb\"\x1e\n\x08Purchase\x12\x12\n\nclaim_hash\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PURCHASE = _descriptor.Descriptor(
  name='Purchase',
  full_name='pb.Purchase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim_hash', full_name='pb.Purchase.claim_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Purchase'] = _PURCHASE

Purchase = _reflection.GeneratedProtocolMessageType('Purchase', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASE,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:pb.Purchase)
  ))
_sym_db.RegisterMessage(Purchase)


# @@protoc_insertion_point(module_scope)
