# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringmap_ext.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stringmap_ext.proto\x12\x03\x65xt\"\x82\x01\n\tStringMap\x12 \n\x01s\x18\x01 \x03(\x0b\x32\x15.ext.StringMap.SEntry\x1a\x13\n\x05Value\x12\n\n\x02vs\x18\x01 \x03(\t\x1a>\n\x06SEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.ext.StringMap.Value:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stringmap_ext_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGMAP_SENTRY._options = None
  _STRINGMAP_SENTRY._serialized_options = b'8\001'
  _STRINGMAP._serialized_start=29
  _STRINGMAP._serialized_end=159
  _STRINGMAP_VALUE._serialized_start=76
  _STRINGMAP_VALUE._serialized_end=95
  _STRINGMAP_SENTRY._serialized_start=97
  _STRINGMAP_SENTRY._serialized_end=159
# @@protoc_insertion_point(module_scope)
