name: lbry
description: LBRY SDK in Dart.
version: 0.0.1
homepage: https://lbry.com
author: LBRY Inc. <hello@lbry.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  path: ^1.4.1
  protobuf: ^0.13.12

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  protoc_plugin: ^17.0.2
