CLAIM_TYPES = {
    'stream': 1,
    'channel': 2,
}

STREAM_TYPES = {
    'video': 1,
    'audio': 2,
    'image': 3,
    'document': 4,
    'binary': 5,
    'model': 6
}

MATURE_TAGS = [
    'nsfw', 'porn', 'xxx', 'mature', 'adult', 'sex'
]

COMMON_TAGS = {
    "gaming": "gaming",
    "people & blogs": "people_and_blogs",
    "pop culture": "pop_culture",
    "entertainment": "entertainment",
    "technology": "technology",
    "music": "music",
    "funny": "funny",
    "education": "education",
    "learning": "learning",
    "news": "news",
    "gameplay": "gameplay",
    "science & technology": "science_and_technology",
    "playstation 4": "playstation_4",
    "beliefs": "beliefs",
    "nature": "nature",
    "news & politics": "news_and_politics",
    "comedy": "comedy",
    "games": "games",
    "sony interactive entertainment": "sony_interactive_entertainment",
    "film & animation": "film_and_animation",
    "game": "game",
    "howto & style": "howto_and_style",
    "weapons": "weapons",
    "blockchain": "blockchain",
    "video game": "video_game",
    "sports": "sports",
    "walkthrough": "walkthrough",
    "ps4live": "ps4live",
    "art": "art",
    "pc": "pc",
    "economics": "economics",
    "automotive": "automotive",
    "minecraft": "minecraft",
    "playthrough": "playthrough",
    "ps4share": "ps4share",
    "tutorial": "tutorial",
    "play": "play",
    "twitch": "twitch",
    "how to": "how_to",
    "ps4": "ps4",
    "bitcoin": "bitcoin",
    "fortnite": "fortnite",
    "commentary": "commentary",
    "lets play": "lets_play",
    "fun": "fun",
    "politics": "politics",
    "xbox": "xbox",
    "autos & vehicles": "autos_and_vehicles",
    "travel & events": "travel_and_events",
    "food": "food",
    "science": "science",
    "mature": "mature",
    "xbox one": "xbox_one",
    "liberal": "liberal",
    "democrat": "democrat",
    "progressive": "progressive",
    "survival": "survival",
    "nonprofits & activism": "nonprofits_and_activism",
    "cryptocurrency": "cryptocurrency",
    "playstation": "playstation",
    "nintendo": "nintendo",
    "government": "government",
    "steam": "steam",
    "podcast": "podcast",
    "horror": "horror",
    "conservative": "conservative",
    "reaction": "reaction",
    "trailer": "trailer",
    "love": "love",
    "cnn": "cnn",
    "republican": "republican",
    "gamer": "gamer",
    "political": "political",
    "hangoutsonair": "hangoutsonair",
    "hoa": "hoa",
    "msnbc": "msnbc",
    "cbs": "cbs",
    "donald trump": "donald_trump",
    "fiction": "fiction",
    "fox news": "fox_news",
    "anime": "anime",
    "crypto": "crypto",
    "ethereum": "ethereum",
    "call of duty": "call_of_duty",
    "multiplayer": "multiplayer",
    "android": "android",
    "epic": "epic",
    "rpg": "rpg",
    "adventure": "adventure",
    "secular talk": "secular_talk",
    "btc": "btc",
    "atheist": "atheist",
    "atheism": "atheism",
    "ps3": "ps3",
    "video games": "video_games",
    "cod": "cod",
    "agnostic": "agnostic",
    "movie": "movie",
    "online": "online",
    "fps": "fps",
    "mod": "mod",
    "reviews": "reviews",
    "sharefactory": "sharefactory",
    "world": "world",
    "space": "space",
    "hilarious": "hilarious",
    "stream": "stream",
    "lol": "lol",
    "sony": "sony",
    "god": "god",
    "lets": "lets",
    "dance": "dance",
    "pvp": "pvp",
    "tech": "tech",
    "zombies": "zombies",
    "pokemon": "pokemon",
    "fail": "fail",
    "xbox 360": "xbox_360",
    "film": "film",
    "unboxing": "unboxing",
    "animation": "animation",
    "travel": "travel",
    "money": "money",
    "wwe": "wwe",
    "how": "how",
    "mods": "mods",
    "pubg": "pubg",
    "indie": "indie",
    "strategy": "strategy",
    "history": "history",
    "rap": "rap",
    "ios": "ios",
    "sony computer entertainment": "sony_computer_entertainment",
    "mobile": "mobile",
    "trump": "trump",
    "flat earth": "flat_earth",
    "hack": "hack",
    "trap": "trap",
    "fox": "fox",
    "vlogging": "vlogging",
    "news radio": "news_radio",
    "humor": "humor",
    "facebook": "facebook",
    "edm": "edm",
    "fitness": "fitness",
    "vaping": "vaping",
    "hip hop": "hip_hop",
    "secular": "secular",
    "jesus": "jesus",
    "vape": "vape",
    "song": "song",
    "remix": "remix",
    "guitar": "guitar",
    "daily": "daily",
    "mining": "mining",
    "diy": "diy",
    "videogame": "videogame",
    "pets & animals": "pets_and_animals",
    "funny moments": "funny_moments",
    "religion": "religion",
    "death": "death",
    "media": "media",
    "nbc": "nbc",
    "war": "war",
    "freedom": "freedom",
    "viral": "viral",
    "meme": "meme",
    "family": "family",
    "gold": "gold",
    "photography": "photography",
    "chill": "chill",
    "zombie": "zombie",
    "computer": "computer",
    "sniper": "sniper",
    "bible": "bible",
    "linux": "linux",
    "overwatch": "overwatch",
    "pro": "pro",
    "dragon": "dragon",
    "litecoin": "litecoin",
    "gta": "gta",
    "iphone": "iphone",
    "house": "house",
    "bass": "bass",
    "bitcoin news": "bitcoin_news",
    "wii": "wii",
    "crash": "crash",
    "league of legends": "league_of_legends",
    "grand theft auto v": "grand_theft_auto_v",
    "mario": "mario",
    "mmorpg": "mmorpg",
    "satire": "satire",
    "fire": "fire",
    "racing": "racing",
    "apple": "apple",
    "health": "health",
    "instrumental": "instrumental",
    "destiny": "destiny",
    "truth": "truth",
    "race": "race"
}
