# This is an example daemon_settings.yml file.
# See https://lbry.tech/resources/daemon-settings for all configuration keys and values

share_usage_data: True

lbryum_servers:
  - lbryumx1.lbry.io:50001
  - lbryumx2.lbry.io:50001

blockchain_name: lbrycrd_main

data_dir: /home/lbry/.lbrynet
download_directory: /home/lbry/downloads

delete_blobs_on_remove: True
dht_node_port: 4444
peer_port: 3333
use_upnp: True

use_auth_http: True
use_https: True

#components_to_skip:
#  - peer_protocol_server
#  - hash_announcer
#  - dht
