all: _blockchain_dock.py _output_dock.py
_blockchain_dock.py: blockchain_dock.ui
	pyside2-uic -d blockchain_dock.ui -o _blockchain_dock.py
_output_dock.py: output_dock.ui
	pyside2-uic -d output_dock.ui -o _output_dock.py
